---
- name: Converge
  hosts: ubi7
  tasks:
    - name: "Include ansible-role-php-toolchain"
      include_role:
        name: "ansible-role-php-toolchain"
      vars:
        php_toolchain_url: https://s3.amazonaws.com/boxes.10gen.com/build/toolchain-drivers/mongo-php-driver/php-toolchain-rhel70-64bit-37dbfb7b800408897e2dbb6c85ae9e67ce6f7c49.tar.gz

- name: Converge
  hosts: debian9
  tasks:
    - name: "Include ansible-role-php-toolchain"
      include_role:
        name: "ansible-role-php-toolchain"
      vars:
        php_toolchain_url: https://s3.amazonaws.com/boxes.10gen.com/build/toolchain-drivers/mongo-php-driver/php-toolchain-debian92-64bit-37dbfb7b800408897e2dbb6c85ae9e67ce6f7c49.tar.gz

- name: Converge
  hosts: ubuntu1604
  tasks:
    - name: "Include ansible-role-php-toolchain"
      include_role:
        name: "ansible-role-php-toolchain"
      vars:
        php_toolchain_url: https://s3.amazonaws.com/boxes.10gen.com/build/toolchain-drivers/mongo-php-driver/php-toolchain-ubuntu1604-64bit-37dbfb7b800408897e2dbb6c85ae9e67ce6f7c49.tar.gz
