---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian9
    image: debian:9
    pre_build_image: true
  - name: ubuntu1604
    image: ubuntu:16.04
provisioner:
  name: ansible
verifier:
  name: testinfra
